### ISSUE TITLE
Password Length Change

### ISSUE THREAD

**Issue by edamame007** [DanielSantoro/wc-password-strength-settings#6]
Hi,
It would be better if I can change the password length requirement. Even if I choose Level 3 Weak or even Level 1 Anything, it still requires minimum of 12 characters long, of which I don't think it is weak.

Do you also have the definition of each level?

**Comment by DanielSantoro** [comment]
Hi there!

The password length isn't actually required to be twelve characters - that's the suggestion text added by WooCommerce. That's something I'm looking to edit in the next version (see the issue here: https://github.com/DanielSantoro/wc-password-strength-settings/issues/5) so you can change that text.

There isn't a clear cut definition of each level, as it's determined by the algorithm WordPress uses called [zxcvbn](https://github.com/dropbox/zxcvbn), developed by Dropbox. Here are some examples, though:

* **Level 1 Password (Very Weak):** a
* **Level 2 Password (Weak):** djwo1n
* **Level 3 Password (Medium):** djwo1n! (the special character itself didn't actually raise the difficulty on its own, but it did bring it up to the next level. More characters added to the Level 2 password would have had the same effect. Capitalization doesn't have much impact.)
* **Level 4 Password (Strong):** donthackme (even though I'd consider this a very poor password choice, the calculator can't think like we do, so if a computer was trying to brute force into your account this would be a relatively strong password)
* **Level 5 Password (Very Strong):** can coaster desk 3 (multiple short words tend to make the strongest passwords)

Hopefully this helps, and I'll look into changing that hint text. :)
